# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs'
# platform :ios, '9.0'

target 'OCTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OCTest
  pod 'AFNetworking','~>2.5'
  pod 'SVProgressHUD'


end
